#!/usr/bin/env bash
# GOOD Luck
bx=1

while [[ $bx -le 10 ]]
do
	if [[ $bx -eq 4 ]];
then
		echo "bad luck";
	elif [[ $bx -eq 8 ]]; then
		echo "good luck";
	else
		echo "Best School";
	fi
	bx=$(( bx+1 ));
done
