#!/usr/bin/env bash
# BAD LUCK
bx=1
while [ $bx -le 20 ]
do
  echo "$bx";
  case $bx in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( bx++ ));
done
