#!/bin/bash

# Name of the private key
PRIVATE_KEY="school"

# Number of bits in the created key
KEY_BITS=4096

# Passphrase for the key
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $PRIVATE_KEY -P $PASSPHRASE
